name: E2E tests

on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
    branches:
      - master
      - v6
    paths:
      - "Dockerfile"
      - "**.go"
      - "!**_test.go" # exclude test files to ignore unit test changes
      - "e2e/**_test.go" # include test files in e2e again
      - ".github/workflows/e2e-tests.yaml"

env:
  GO111MODULE: on
  GOFLAGS: -mod=vendor

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Harden Runner
      uses: step-security/harden-runner@rc
      with:
        egress-policy: block
        allowed-endpoints: >
          auth.docker.io:443
          charts.devspace.sh:443
          dl-cdn.alpinelinux.org:443
          gcr.io:443
          ghcr.io:443
          github.com:443
          index.docker.io:443
          objects.githubusercontent.com:443
          pkg-containers.githubusercontent.com:443
          production.cloudflare.docker.com:443
          raw.githubusercontent.com:443
          registry-1.docker.io:443
          storage.googleapis.com:443

    - name: Checkout repo
      uses: actions/checkout@v2

    # Creates KinD with using k8s versions from the matrix above
    - name: Set up kind with K8s version v1.22.4
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.11.1"
        image: kindest/node:v1.22.4
    - name: Testing kind cluster set-up
      run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build devspacehelper
      run: |
        mkdir -p ~/.devspace/devspacehelper/latest
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-extldflags=-static" -o ~/.devspace/devspacehelper/latest/devspacehelper helper/main.go
        chmod +x ~/.devspace/devspacehelper/latest/devspacehelper
      env:
        GOPATH: /Users/runner/work/devspace/go

    - name: e2e test
      working-directory: ./e2e
      run: |
        go test -v -ginkgo.v -timeout 3600s
